application: cha201204
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: static/css
  
- url: /bootstrap
  static_dir: static/bootstrap

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: .*
  script: main.py
