<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" class="active" href="#">William's Oriental Tea</a>
          <div class="nav-collapse">
            <ul class="nav">
              <!--<li class="active"><a href="#">Home</a></li>-->
              <li><a href="#about">Köpinformation</a></li>
              <li><a href="#about"></a></li>
              <li><a href="#contact">Kontakta oss</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
